name: Print GitHub Context

on:
  push:
    branches:
      - main
  issues:
    types: [opened]
  workflow_dispatch:

# on:
#   schedule:
#     - cron: '0 */1 * * *' # Runs every 1 hour
#     - cron: '0 */6 * * *' # Runs every 6 hours
#     # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#scheduled-events

jobs:
  print_github_context:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Print repo name
      run: echo ${{ github.repository }}

    # this only works when the workflow is triggered by an issue
    - name: Print number of issues
      run: echo ${{ github.event.issue.number }}

    # this only works when the workflow is triggered by an issue
    - name: Print issue context
      # jq is a JSON processor. Here, it formats JSON output, making it more human-readable.
      run: echo '${{ toJSON(github.event.issue) }}' | jq
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Print GitHub context
      run: echo '${{ toJSON(github.event) }}' | jq
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
