name: Update Lulu's GitHub Profile

on:
  push:
    branches:
      - main
  workflow_dispatch:

# on:
#   schedule:
#     - cron: '0 */1 * * *' # Runs every 1 hour

jobs:
  update_posts:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Print repo
      run: echo ${{ github.repository }}

    - name: Print issue
      run: echo ${{github.event.issue}}

    - name: Print event
      run: echo ${{github.event}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
