name: Update GitHub Profile Picture

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_profile_picture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Profile README
        run: |
          # Append an <img> tag with the fetched image URL to the README
          echo "<img src=\"https://picsum.photos/200/300/?random\" alt=\"Random Image\">" >> README.md
          git config --global user.name "Lulu Cao"
          git config --global user.email "lulu.cao.her@gmail.com"
          git add README.md
          git commit -m "Update profile README with a random picture"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
