name: Update GitHub Profile Quote

on:
  workflow_dispatch:

jobs:
  update_profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Random Quote
        id: fetch-quote
        run: |
          QUOTE=$(curl -s https://api.quotable.io/random | jq -r '.content')
          echo "::set-output name=quote::$QUOTE"
        shell: bash

      - name: Update Profile README
        run: |
          # Append the fetched quote
          echo -e "${{ steps.fetch-quote.outputs.quote }}\n" >> README.md
          git config --global user.name "Lulu Cao"
          git config --global user.email "lulu.cao.her@gmail.com"
          git add README.md
          git commit -m "Update profile README with a random quote"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
