name: Update GitHub Profile Picture

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#scheduled-events

jobs:
  update_profile_picture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Profile README
        run: |
          # Append an <img> tag with the fetched image URL to the README
          echo "<img src=\"https://picsum.photos/200/300/?random\" alt=\"Random Image\">" >> README.md
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git add README.md
          git commit -m "Update profile README with a random picture"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
